# Generated by Django 2.1.1 on 2018-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kempo', '0003_technique_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
