# Generated by Django 2.1.1 on 2018-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kempo', '0007_technique_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.CharField(default='OTHER', max_length=20),
        ),
    ]
